### ISSUE TITLE
Submission feedback

### ISSUE THREAD

**Issue by chrisbay** [fungjj92/thisisthemodernweb#1]
This turned out really well!

A couple of very minor things:
- You have your CSS <link> tags outside of your <head> (between the opening <html> and <head>). Move these inside the <head>
- Your floated element, the #ceviche div, would be much better as a <figure> with <caption> or <figcaption>

Other than that, this looks awesome. I love the layout and transitions!

**Comment by fungjj92** [comment]
Thanks! I only made the #ceviche div a floated element because of the project spec, I also think it would be better as a figure & caption. 

Made the changes and submitted a pull req.

**Comment by chrisbay** [comment]
Thanks!
